# Generated by Django 4.2.1 on 2023-06-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(to='excerpts.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.TextField()),
                ('metadata', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(to='excerpts.character')),
                ('projects', models.ManyToManyField(to='excerpts.project')),
                ('tags', models.ManyToManyField(to='excerpts.tag')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='projects',
            field=models.ManyToManyField(to='excerpts.project'),
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(to='excerpts.tag'),
        ),
    ]
