# Generated by Django 4.2.4 on 2023-08-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
