# Generated by Django 4.2.1 on 2023-06-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0002_excerptsimilarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excerptsimilarity',
            name='spacy_similarity',
        ),
    ]
