# Generated by Django 4.2.4 on 2023-08-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0003_job_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerptAutoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbert_similarity', models.FloatField()),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excerpts.excerpt')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excerpts.tag')),
            ],
        ),
    ]
