# Generated by Django 4.2.4 on 2023-08-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0004_excerptautotag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerptautotag',
            name='excerpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autotags', to='excerpts.excerpt'),
        ),
    ]
