# Generated by Django 4.2.13 on 2024-07-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0005_alter_excerptautotag_excerpt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Entity',
        ),
        migrations.RenameField(
            model_name='excerpt',
            old_name='characters',
            new_name='entities',
        ),
    ]
