# Generated by Django 4.2.1 on 2023-06-18 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0006_alter_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='excerpts.tagtype'),
        ),
    ]
