# Generated by Django 4.2.19 on 2025-03-03 01:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("excerpts", "0007_concept_relationshiptype_entityrelationship_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="excerpt",
            name="entities",
        ),
        migrations.AddField(
            model_name="entityrelationship",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entityrelationship",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="excerptrelationship",
            name="relationship_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="excerpts.relationshiptype",
            ),
        ),
        migrations.AddField(
            model_name="relationshiptype",
            name="applicable_contexts",
            field=models.CharField(
                default="EE,XX,EX",
                help_text="Comma-separated list of contexts where this relationship type can be used",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="entityrelationship",
            name="relationship_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="excerpts.relationshiptype",
            ),
        ),
        migrations.CreateModel(
            name="EntityExcerptRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excerpt_relationships",
                        to="excerpts.entity",
                    ),
                ),
                (
                    "excerpt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_relationships",
                        to="excerpts.excerpt",
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="excerpts.relationshiptype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="related_excerpts",
            field=models.ManyToManyField(
                related_name="related_entities",
                through="excerpts.EntityExcerptRelationship",
                to="excerpts.excerpt",
            ),
        ),
    ]
