# Generated by Django 4.2.1 on 2023-06-30 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0008_excerptrelationship_remove_character_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excerptrelationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excerptrelationship',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
