# Generated by Django 4.2.1 on 2023-06-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('excerpt', models.TextField()),
                ('metadata', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(to='excerpts.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(to='excerpts.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcerptTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_autotag', models.BooleanField(default=False)),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excerpts.excerpt')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excerpts.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ExcerptSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbert_similarity', models.FloatField()),
                ('excerpt1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpt1', to='excerpts.excerpt')),
                ('excerpt2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpt2', to='excerpts.excerpt')),
            ],
        ),
        migrations.AddField(
            model_name='excerpt',
            name='projects',
            field=models.ManyToManyField(to='excerpts.project'),
        ),
        migrations.AddField(
            model_name='excerpt',
            name='tags',
            field=models.ManyToManyField(through='excerpts.ExcerptTag', to='excerpts.tag'),
        ),
        migrations.AddField(
            model_name='character',
            name='projects',
            field=models.ManyToManyField(to='excerpts.project'),
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(to='excerpts.tag'),
        ),
    ]
