# Generated by Django 4.2.1 on 2023-06-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerpts', '0002_rename_excerpt_excerpt_content_excerptversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='tags',
            field=models.ManyToManyField(related_name='excerpts', through='excerpts.ExcerptTag', to='excerpts.tag'),
        ),
    ]
